# Generated by Django 5.0 on 2024-03-17 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0004_internship_include_what_you_will_learn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('internship_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_data')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('internship_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_data')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_lesson')),
            ],
        ),
    ]
