# Generated by Django 5.0 on 2024-03-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0005_internship_lesson_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Internship_Topic',
        ),
    ]
