# Generated by Django 5.0 on 2024-03-17 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0007_remove_internship_topic_internship_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_id', models.CharField(default='', max_length=25)),
                ('linkedin_id', models.CharField(blank=True, max_length=500, null=True)),
                ('github_id', models.CharField(blank=True, max_length=5000, null=True)),
                ('qualification', models.CharField(blank=True, max_length=5000, null=True)),
                ('stream', models.CharField(blank=True, max_length=5000, null=True)),
                ('college_name', models.CharField(blank=True, max_length=50000, null=True)),
                ('passing_year', models.CharField(blank=True, max_length=50, null=True)),
                ('learn_path_document', models.FileField(blank=True, null=True, upload_to='image/download/uploads/learn_path_document/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='image/download/uploads/offer_later/')),
                ('allocated_task', models.FileField(blank=True, null=True, upload_to='image/download/uploads/allocated_task/')),
                ('task_submission', models.FileField(blank=True, null=True, upload_to='image/download/uploads/task_submission/')),
                ('internship_certificate', models.FileField(blank=True, null=True, upload_to='image/download/uploads/internship_certificate/')),
                ('lor_letter', models.FileField(blank=True, null=True, upload_to='image/download/uploads/lor_letter/')),
                ('swags_form', models.FileField(blank=True, null=True, upload_to='image/download/uploads/swags_form/')),
                ('internship_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_data')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
