# Generated by Django 5.0 on 2024-03-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0009_passing_year_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_student',
            name='task_submission',
        ),
    ]
