# Generated by Django 5.0 on 2024-03-18 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0010_remove_internship_student_task_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_topic',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='image/download/uploads/internship_video/'),
        ),
        migrations.AddField(
            model_name='internship_topic',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='image/download/uploads/internship_video_thumbnail/'),
        ),
        migrations.CreateModel(
            name='Internship_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('internship_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_data')),
                ('internship_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
