# Generated by Django 5.0 on 2024-03-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0011_internship_topic_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_data',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='internship_data',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
