# Generated by Django 5.0 on 2024-03-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0014_internship_question_internship_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_quiz',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='internship_quiz',
            name='quiz_file',
            field=models.FileField(upload_to='Questions_Files'),
        ),
        migrations.AlterField(
            model_name='internship_quiz',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
