# Generated by Django 5.0 on 2024-03-18 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0016_alter_internship_quiz_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrank',
            name='internship_quiz_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_quizsubmission'),
        ),
    ]
