# Generated by Django 5.0 on 2024-03-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0021_rename_assignment_download_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_student',
            name='github_id',
        ),
        migrations.RemoveField(
            model_name='internship_student',
            name='linkedin_id',
        ),
    ]
