# Generated by Django 5.0 on 2024-03-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0028_remove_internship_userrank_total_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_userrank',
            name='quiz_submission',
        ),
        migrations.AddField(
            model_name='internship_userrank',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
