# Generated by Django 5.0 on 2024-03-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0029_remove_internship_userrank_quiz_submission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship_userrank',
            old_name='total_questions',
            new_name='score',
        ),
        migrations.AddField(
            model_name='internship_userrank',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
