# Generated by Django 4.2.11 on 2024-04-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0031_internship_task_submission_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_student',
            name='passing_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Internship_app.passing_year'),
        ),
        migrations.AlterField(
            model_name='internship_student',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Internship_app.qualification'),
        ),
    ]
