# Generated by Django 5.0.6 on 2024-06-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0035_remove_internship_allocated_task_internship_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='what_you_will_learn',
            name='internship_data',
        ),
        migrations.DeleteModel(
            name='Internship_Include',
        ),
        migrations.DeleteModel(
            name='What_you_will_learn',
        ),
    ]
