# Generated by Django 5.0.6 on 2024-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0036_remove_what_you_will_learn_internship_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_topic',
            name='video_1080p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='image/download/uploads/internship_video/original/1080p/'),
        ),
        migrations.AddField(
            model_name='internship_topic',
            name='video_360p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='image/download/uploads/internship_video/original/360p/'),
        ),
        migrations.AddField(
            model_name='internship_topic',
            name='video_480p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='image/download/uploads/internship_video/original/480p/'),
        ),
        migrations.AddField(
            model_name='internship_topic',
            name='video_720p',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='image/download/uploads/internship_video/original/720p/'),
        ),
        migrations.AlterField(
            model_name='internship_topic',
            name='video',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='image/download/uploads/internship_video/original/'),
        ),
    ]
