# Generated by Django 5.0 on 2024-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_image', models.ImageField(upload_to='image/download/uploads/internship_image')),
                ('internship_title', models.CharField(max_length=50)),
                ('internship_position', models.CharField(max_length=50)),
                ('internship_location', models.CharField(max_length=50)),
                ('internship_duration', models.CharField(max_length=50)),
                ('internship_description', models.TextField(blank=True, default='', max_length=50, null=True)),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('2', 'INACTIVE')], default=1, max_length=25)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
