# Generated by Django 5.0 on 2024-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_data',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=500, null=True),
        ),
    ]
