# Generated by Django 5.0 on 2024-03-17 12:09

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0002_internship_data_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_data',
            name='internship_description',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
