# Generated by Django 5.0 on 2024-03-17 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0006_rename_topic_internship_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship_topic',
            name='internship_data',
        ),
    ]
