# Generated by Django 5.0 on 2024-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0008_internship_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passing_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_year', models.CharField(max_length=2000)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=2000)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
