# Generated by Django 5.0 on 2024-03-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0012_internship_data_discount_internship_data_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_data',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
