# Generated by Django 5.0 on 2024-03-19 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0018_remove_userrank_internship_quiz_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_file', models.FileField(upload_to='image/download/uploads/assignment_file')),
                ('status', models.CharField(choices=[('1', 'ACTIVE'), ('2', 'INACTIVE')], default=1, max_length=25)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('internship_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_data')),
            ],
        ),
    ]
