# Generated by Django 5.0 on 2024-03-19 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0019_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='internship_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_data'),
        ),
    ]
