# Generated by Django 5.0 on 2024-03-19 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0023_user_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_payment',
            name='user_internship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Internship_app.user_internship'),
        ),
    ]
