# Generated by Django 5.0 on 2024-03-19 19:09

import django.db.models.deletion
import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0024_internship_payment_user_internship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('answer', froala_editor.fields.FroalaField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('internship_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_data')),
            ],
        ),
    ]
