# Generated by Django 4.2.11 on 2024-05-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0032_alter_internship_student_passing_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship_Allocated_Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_task', models.FileField(blank=True, null=True, upload_to='image/download/uploads/allocated_task/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship_Learn_Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_path_document', models.FileField(blank=True, null=True, upload_to='image/download/uploads/learn_path_document/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='internship_student',
            name='allocated_task',
        ),
        migrations.RemoveField(
            model_name='internship_student',
            name='learn_path_document',
        ),
    ]
