# Generated by Django 4.2.11 on 2024-05-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Internship_app', '0033_internship_allocated_task_internship_learn_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship_allocated_task',
            name='internship_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_data'),
        ),
        migrations.AddField(
            model_name='internship_learn_path',
            name='internship_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Internship_app.internship_data'),
        ),
    ]
