# Generated by Django 5.0 on 2024-03-06 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_intern_LMS_app', '0002_customeuser_facebook_customeuser_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Login_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100)),
                ('browser_info', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
