# Generated by Django 5.0 on 2024-04-04 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_intern_LMS_app', '0009_customsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
