# Generated by Django 5.0 on 2024-04-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_intern_LMS_app', '0010_delete_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achiever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievers_image', models.ImageField(upload_to='image/download/uploads/achievers_image')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_image', models.ImageField(upload_to='image/download/uploads/testimonial_image')),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
