# Generated by Django 4.2.11 on 2024-04-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_intern_LMS_app', '0011_achiever_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('media_file', models.ImageField(upload_to='image/download/uploads/media_file')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
