# Generated by Django 5.0.6 on 2024-06-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_intern_LMS_app', '0012_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achiever',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='session',
        ),
        migrations.RemoveField(
            model_name='customsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.RemoveField(
            model_name='user_login_log',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomSession',
        ),
        migrations.DeleteModel(
            name='User_Login_Log',
        ),
    ]
