# Generated by Django 5.0 on 2024-02-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_intern_LMS_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='facebook',
            field=models.URLField(blank=True, max_length=250000000000000000000000, null=True),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='instagram',
            field=models.URLField(blank=True, max_length=250000000000000000000000, null=True),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='linkedin',
            field=models.URLField(blank=True, max_length=250000000000000000000000, null=True),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='twitter',
            field=models.URLField(blank=True, max_length=250000000000000000000000, null=True),
        ),
        migrations.AddField(
            model_name='customeuser',
            name='youtube',
            field=models.URLField(blank=True, max_length=250000000000000000000000, null=True),
        ),
        migrations.DeleteModel(
            name='User_Social_Proile',
        ),
    ]
