# Generated by Django 5.0 on 2024-03-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_intern_LMS_app', '0003_user_login_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login_log',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user_login_log',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
